CREATE TABLE flash_projects (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  project_name TEXT NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP,
     user_id INTEGER REFERENCES flash_users(id)
    ON DELETE SET NULL
);


